dynamic-http-proxy:
  labels:
    io.rancher.sidekicks: letsencrypt-companion
    io.rancher.scheduler.affinity:host_label: io.rancher.host.hostname=${hostname}
  image: jwilder/nginx-proxy
  container_name: nginx
  ports:
    - "${http_port}:80"
    - "${https_port}:443"
  volumes:
    - /etc/nginx/conf.d
    - /var/certs:/etc/nginx/certs:ro
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - /etc/nginx/vhost.d
    - /usr/share/nginx/html

letsencrypt-companion:
  image: jrcs/letsencrypt-nginx-proxy-companion
  container_name: letsencrypt-companion
  volumes_from:
      - nginx
  volumes:
    - /var/certs:/etc/nginx/certs:rw
    - /var/run/docker.sock:/var/run/docker.sock:ro
