.catalog:
  name: Owncloud
  version: 0.1
  description: |
    Owncloud.
  questions:
    - variable: "MYSQL_ROOT_PASSWORD"
      label: "MySQL root password"
      type: "password"
      required: true
      default: "cloudroot"
      description: "MySQL root user pasword"
    - variable: "MYSQL_DATABASE_NAME"
      label: "MySQL database name"
      type: "string"
      required: true
      default: "owncloud"
      description: "MySQL database name"
    - variable: "MYSQL_USER"
      label: "MySQL user"
      type: "string"
      required: true
      default: "cloud"
      description: "MySQL user"
    - variable: "MYSQL_PASSWORD"
      label: "MySQL password"
      type: "password"
      required: true
      default: "cloud"
      description: "MySQL user password"
    - variable: "DATA_VOLUME"
      label: "Data volume"
      type: "string"
      required: true
      default: "/var/docker/owncloud-data"
      description: "Volume for persistent storage of service data"
    - variable: "CONFIG_VOLUME"
      label: "Configuration volume"
      type: "string"
      required: true
      default: "/var/docker/owncloud-config"
      description: "Volume for persistent storage of service configuration data"
    - variable: "DB_VOLUME"
      label: "Database volume"
      type: "string"
      required: true
      default: "/var/docker/owncloud-dbdata"
      description: "Volume for persistent storage of database data"
    - variable: "VHOST_DOMAIN_NAME"
      label: "Virtual host domain name"
      type: "string"
      required: false
      default: ""
      description: "Domain name to use for the service if using dynamic proxy"
    - variable: "LETSENCRYPT_EMAIL"
      label: "Letsencrypt e-mail"
      type: "string"
      required: false
      default: ""
      description: "Letsencrypt e-mail if using dynamic proxy"
