registry:
  restart: always
  image: registry:2
  ports:
    - ${PORT}:5000
  environment:
    REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
    REGISTRY_HTTP_TLS_KEY: /certs/domain.key
    REGISTRY_AUTH: htpasswd
    REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
  volumes:
    - ${DATA_VOLUME}/data:/var/lib/registry
    - ${DATA_VOLUME}/certs:/certs
    - ${DATA_VOLUME}/auth:/auth
