nginx-proxy:
  labels:
    io.rancher.sidekicks: letsencrypt-companion, nginx-gen
    io.rancher.scheduler.affinity:host_label: ${AFF_HOST_LABELS}
  image: jwilder/nginx-proxy
  container_name: nginx-proxy
  ports:
    - "${HTTP_PORT}:80"
    - "${HTTPS_PORT}:443"
  volumes:
    - "/etc/nginx/conf.d"
    - "/etc/nginx/vhost.d"
    - "/usr/share/nginx/html"
    - "./volumes/proxy/certs:/etc/nginx/certs:ro"

nginx-gen:
  image: jwilder/docker-gen
  container_name: nginx-gen
  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock:ro"
    - "./volumes/proxy/templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro"
  volumes_from:
    - nginx-proxy
  entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

letsencrypt-companion:
  image: jrcs/letsencrypt-nginx-proxy-companion
  container_name: letsencrypt-companion
  volumes_from:
      - nginx-proxy
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock:ro"
    - "./volumes/proxy/certs:/etc/nginx/certs:rw"
  environment:
    - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
