gogs-server:
  labels:
    rap.host: ${VHOST_DOMAIN_NAME}
    rap.le_host: ${VHOST_DOMAIN_NAME}
    rap.le_email: ${LETSENCRYPT_EMAIL}
    rap.port: 3000
  image: gogs/gogs:0.9.141
  container_name: gogs-server
  ports:
    - "${SSH_PORT}:22"
  volumes:
    - ${DATA_VOLUME}:/data
  links:
    - gogs-db:mysql
  environment:
    - VIRTUAL_HOST=${VHOST_DOMAIN_NAME}
    - VIRTUAL_PORT=3000
    - LETSENCRYPT_HOST=${VHOST_DOMAIN_NAME}
    - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}

gogs-db:
  image: mysql:5.6
  container_name: gogs-db
  volumes:
    - ${DB_VOLUME}:/var/lib/mysql
  ports:
    - "${MYSQL_PORT}:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    - MYSQL_DATABASE=${MYSQL_DATABASE_NAME}
    - MYSQL_USER=${MYSQL_USER}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
