.catalog:
  name: Gogs
  version: 0.1
  description: |
    Gogs Git server.
  questions:
    - variable: "HTTP_PORT"
      label: "HTTP port"
      required: true
      type: "int"
      default: 3000
      description: "HTTP port"
    - variable: "SSH_PORT"
      label: "SSH port"
      type: "int"
      required: true
      default: 10022
      description: "SSH port"
    - variable: "MYSQL_PORT"
      label: "MySQL port"
      type: "int"
      required: true
      default: 3400
      description: "MySQL port"
    - variable: "MYSQL_ROOT_PASSWORD"
      label: "MySQL root password"
      type: "password"
      required: true
      default: "gogsroot"
      description: "MySQL root user pasword"
    - variable: "MYSQL_DATABASE_NAME"
      label: "MySQL database name"
      type: "string"
      required: true
      default: "gogs"
      description: "MySQL database name"
    - variable: "MYSQL_USER"
      label: "MySQL user"
      type: "string"
      required: true
      default: "gogs"
      description: "MySQL Gogs user"
    - variable: "MYSQL_PASSWORD"
      label: "MySQL password"
      type: "password"
      required: true
      default: "gogs"
      description: "MySQL Gogs user password"
    - variable: "DATA_VOLUME"
      label: "Data volume"
      type: "string"
      required: true
      default: "/var/docker/gogs-data"
      description: "Volume for persistent storage of service data"
    - variable: "DB_VOLUME"
      label: "Database volume"
      type: "string"
      required: true
      default: "/var/docker/gogs-dbdata"
      description: "Volume for persistent storage of database data"
    - variable: "AFF_HOST_LABELS"
      label: "Affinity host labels"
      type: "string"
      required: false
      default: "key1=value1,key2=value2"
      description: "Example: key1=value1,key2=value2, etc..."
    - variable: "VHOST_DOMAIN_NAME"
      label: "Virtual host domain name"
      type: "string"
      required: false
      default: ""
      description: "Domain name to use for the service if using dynamic proxy"
    - variable: "LETSENCRYPT_EMAIL"
      label: "Letsencrypt e-mail"
      type: "string"
      required: false
      default: ""
      description: "Letsencrypt e-mail if using dynamic proxy"
