nodered-server:
  labels:
    rap.host: ${VHOST_DOMAIN_NAME}
    rap.le_host: ${VHOST_DOMAIN_NAME}
    rap.le_email: ${LETSENCRYPT_EMAIL}
  image: nodered/node-red-docker
  ports:
    - "${HTTP_PORT}:1880"
  expose:
    - "80"
  volumes:
    - ${DATA_VOLUME}:/data
  environment:
    - VIRTUAL_HOST=${VHOST_DOMAIN_NAME}
    - VIRTUAL_PORT=1880
    - LETSENCRYPT_HOST=${VHOST_DOMAIN_NAME}
    - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
