.catalog:
  name: Dynamic HTTP Proxy
  version: default
  description: |
    Dynamic HTTP Proxy designed to handle traffic and domains in front of web applications.
  questions:
    - variable: http_port
      label: "HTTP port"
      required: true
      type: "int"
      default: 80
      description: "HTTP port"
    - variable: https_port
      label: "HTTPS port"
      type: "int"
      required: true
      default: 443
      description: "HTTPS port"
    - variable: affinity_host_labels
      label: "Affinity host labels"
      type: "string"
      required: true
      default: "key1=value1,key2=value2"
      description: "Example: key1=value1,key2=value2, etc..."
