.catalog:
  name: Gogs with Convoy storage
  version: 0.1
  description: |
    Gogs Git server with Convoy storage.
  questions:
    - variable: "HTTP_PORT"
      label: "HTTP port"
      required: true
      type: "int"
      default: 3000
      description: "SSH port"
    - variable: "SSH_PORT"
      label: "SSH port"
      type: "int"
      required: true
      default: 10022
      description: "SSH port"
    - variable: "MYSQL_PORT"
      label: "MySQL port"
      type: "int"
      required: true
      default: 3400
      description: "MySQL port"
    - variable: "VOLUME_DRIVER"
      label: "Volume driver"
      type: "enum"
      required: true
      default: "convoy-nfs"
      options:
        - convoy-nfs
        - convoy
      description: "Convoy volume driver"
    - variable: "VOLUME"
      label: "Volume"
      type: "string"
      required: true
      default: "gogs"
      description: "Convoy volume for persisten storage of service data"
    - variable: "AFF_HOST_LABELS"
      label: "Affinity host labels"
      type: "string"
      required: false
      default: "key1=value1,key2=value2"
      description: "Example: key1=value1,key2=value2, etc..."
    - variable: "VHOST_DOMAIN_NAME"
      label: "Virtual host domain name"
      type: "string"
      required: false
      default: ""
      description: "Domain name to use for the service if using dynamic proxy"
